apiVersion: apps/v1
kind: Deployment
metadata:
  name: lwwalkerresume
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lwwalkerresume
  template:
    metadata:
      labels:
        app: lwwalkerresume
    spec:
      containers:
      - name: lwwalkerresume
        image: us-west1-docker.pkg.dev/lwwalker/lwwalkerresume:tag
        ports:
        - containerPort: 80

